CUDA_VISIBLE_DEVICES=0 python train.py \
    --model_name_or_path bert-base-uncased \
    --train_file data/xxx \
    --output_dir result/my-bert-base-uncased \
    --num_train_epochs 3 \
    --per_device_train_batch_size 128 \
    --learning_rate 5e-5 \
    --max_seq_length 512 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --eval_steps 125 \
    --do_train \
    --do_eval \
    --do_predict